CREATE TABLE Inscricoes (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    EventoId UNIQUEIDENTIFIER NOT NULL,
    UsuarioId UNIQUEIDENTIFIER NOT NULL,
    DataInscricao DATETIME NOT NULL DEFAULT GETUTCDATE(),
    Ativa BIT NOT NULL DEFAULT 1
);